language: swift
osx_image: xcode9.3
script:
  - gem install generamba
  - generamba template install
  - yes "Test Author" | generamba gen TestModule yarch --description 'Test Module'
  - xcodebuild clean test -scheme YARCH -workspace YARCH.xcworkspace -destination 'name=iPhone 7,OS=11.2' -enableCodeCoverage YES | xcpretty
  - bundle exec danger
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'YARCH'